### PR TITLE
Support building from pyproject.toml metadata

### LINKED ISSUE #67: Adding a build system
Hi!

Is there interest in adding a build system?  I've been experimenting with adding one to keyboard-center recently for educational purposes, but I would be happy to make a pull request and discuss merging these changes.

### PR DESCRIPTION
**Pull request by aurtzy**
Fixes <https://github.com/zocker-160/keyboard-center/issues/67>.

This adds support for Python packaging build systems based on PEP 517.

The directory structure is reorganized to follow flat-layout, which is automatically recognized by setuptools: <https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#flat-layout>

Move `main.py` to `__init__.py` and turn its contents into a function that can be called from an entrypoint script.

A `MANIFEST.in` file is added so keyboard-center assets are included in the expected installation directory.

Use relative imports to import internal Python modules.

---

I added some basic information to `pyproject.toml`, but feel free to suggest additions/edits that I can include in this pull request.  Python dependencies have been specified in this file, but I'm not sure how to declare dependencies providing `.so` files like hidapi at the moment (if even possible).

The `project.gui-scripts` field at the end of `pyproject.toml` should actually allow for packaging systems to manage this automatically, so I think the starter script that was mentioned in the linked issue could be removed entirely - this may depend on the packaging system used, though.

These changes are not as well tested as I'd like.  Guix is still limited to Python 3.10 at the moment unfortunately, so I had some issues on my end testing this and would appreciate feedback on that end since I don't use much of the featureset either.

...on the bright side, this means I also have working (and perhaps slightly more tested) changes for v1 that I wouldn't mind backporting as well if there's plans to continue maintenance on it :)

Are there any thoughts on adding documentation for installation/building/development?  The [Arch Wiki](https://wiki.archlinux.org/title/Python_package_guidelines), for example, shows one way of installing that we could include in the README.  The best method of installing (python) dependencies for development from `pyproject.toml` that I know of right now is to do `pip install .; pip uninstall keyboard-center` - apparently that's still a WIP PEP or something.

### CODE REVIEW

**Comment by zocker-160** [comment]
First of all thank you very much for this. The file conflicts are new because of my changes to fix the config file bug.

Are relative imports required when using this new directory structure?

**Comment by aurtzy** [comment]
No - absolute imports should be valid as well, like `import keyboard_center.lib.hid` (`keyboard_center` is now considered the top-level module).

I can change them to absolute if you'd prefer when I rebase these changes.

**Comment by zocker-160** [comment]
ok good, you can leave it as is relative imports are fine for now, but I do prefer absolute imports, because I then can reorganize modules without having to update all the imports again.

**Comment by zocker-160** [comment]
thank you very much for this, very appreciated!

**Comment by zocker-160** [comment]
ah and to answer your questions:

- I am not updating v1 anymore unless there is some important bug to be fixed
- Yes adding more instructions to readme how to build / dev is something I am going to do, although it is pretty simple as you only need to install the dependencies and you are good to go

**Pull request merged**
